name: Push 🚀
on:
  push:
    branches:
      - main
      - master
      - 'release/**'
    tags:
      - '*'
jobs:
  check-format:
    uses: obsproject/obs-plugintemplate/.github/workflows/check-format.yaml@master
  build-project:
    needs: check-format
    uses: obsproject/obs-plugintemplate/.github/workflows/build-project.yaml@master
